- name: variables to print
  hosts: web
  vars:
    COURSE: "Devops with Aws"
    DURATION: 120Hrs
    TRAINER: "Sivakumar reddy"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "hi iam leraning {{COURSE}},Duration is{{DURATION}},Trainer:{{TRAINER}}"

  - name: print the information again
    vars:
      COURSE: "ansible"
    ansible.builtin.debug:
      msg: "hi iam leraning {{COURSE}},Duration is{{DURATION}},Trainer:{{TRAINER}}"

  - name: print the information and again
    ansible.builtin.debug:
      msg: "hi iam leraning {{COURSE}},Duration is{{DURATION}},Trainer:{{TRAINER}}"


