- name:
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the cousre details
    ansible.builtin.debug:
      msg: "hi iam learning{{COURSE}},duration is {{DURATION}}, Trainer: {{TRAINER}}"