- name: varibles getting from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
    private: false #not confidential
  - name: DURATION
    prompt: enter the duration time
    private: false #not confidential
  - name: TRAINER
    prompt: enter the trainer name
    private: false #not confidential

  tasks:
  - name: print the course details
    ansible.builtin.debug:
      msg: "hi iam learning{{COURSE}} {{DURATION}}, trainer:{{TRAINER}}"