- name: check the given number with condition
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    propmt: please enter the number
    private: false
  tasks:
  - name: print this if lessthen 10
    ansible.builtin.debug:
      msg: "given number{{my_number}}"is lessthen 10
    when: my_number | int < 10

  - name: print this if greaterthen 10
    ansible.builtin.debug:
      msg: "given number{{my_number}}"is greaterthen 10
    when: my_number | int >= 10