- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: convert to lower case
    ansible.builtin.debug:
      msg: " {{ greeting | lower }}"

  - name: get thr unique values
    vars:
      numbers: [1,2,3,45,4,3,2]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: get the min and max
    vars:
      numbers: [1,2,3,45,4,3,2]
    ansible.builtin.debug:
      msg: "Min: {{ numbers | Min }}, Max: {{ numbers | Max }}"

