- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: convert to lower case
    ansible.builtin.debug:
      msg: " {{ greeting | lower }}"

  - name: get thr unique values
    vars:
      numbers: [1,2,3,45,4,3,2]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: get the min and max
    vars:
      numbers: [1,2,3,45,4,3,2]
    ansible.builtin.debug:
      msg: "Min: {{ numbers | Min }}, Max: {{ numbers | Max }}"

  - name: convert map to list
    vars:
      course:
        name: "DevOps with AWS"
        duration: 120
        trainer: "sivakumar reddy"
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"

  - name: convert list to map
    vars:
      course:
      - { "key": "name","value": "DevOps with AWS" }
      - { "key": "duration","value": 120 }
      - { "key": "trainer","value": "sivakumar reddy" }
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"

  - name: check ip address
    vars:
      myip: "356.168.1.1"
    ansible.builtin.debug:
      msg: "{{ myip | ansible.utils.ipv4 }}"

